### ISSUE TITLE
Unable to add Group

### ISSUE THREAD

**Issue by StanMenten99** [ibrahim-bedir/filament-dynamic-settings-page#4]
Hi,

Unfortunately I'm unable to add a specific setting to a group.
I can't leave it empty and when searching I get the following Console error:
```settings:632 Uncaught TypeError: window.livewire.find is not a function
    at HTMLSelectElement.<anonymous> (settings:632:33)
    at HTMLSelectElement.dispatch (jquery.min.js:3:10316)
    at q.handle (jquery.min.js:3:8343)
    at Object.trigger (jquery.min.js:4:5628)
    at HTMLSelectElement.<anonymous> (jquery.min.js:4:6138)
    at Function.each (jquery.min.js:2:2715)
    at r.fn.init.each (jquery.min.js:2:1003)
    at r.fn.init.trigger (jquery.min.js:4:6114)
    at n.select (select2.min.js:2:35110)
    at o.<anonymous> (select2.min.js:2:35635)
```

The list of already existing groups appear, but I'm also unable to click it.

**Comment by ibrahim-bedir** [comment]
Hi @StanMenten99,

Can you reach me at this e-mail address?
ibrahimbedir43@gmail.com

**Comment by frizcool** [comment]
> Hi,
> 
> Unfortunately I'm unable to add a specific setting to a group. I can't leave it empty and when searching I get the following Console error:
> 
> ```
>     at HTMLSelectElement.<anonymous> (settings:632:33)
>     at HTMLSelectElement.dispatch (jquery.min.js:3:10316)
>     at q.handle (jquery.min.js:3:8343)
>     at Object.trigger (jquery.min.js:4:5628)
>     at HTMLSelectElement.<anonymous> (jquery.min.js:4:6138)
>     at Function.each (jquery.min.js:2:2715)
>     at r.fn.init.each (jquery.min.js:2:1003)
>     at r.fn.init.trigger (jquery.min.js:4:6114)
>     at n.select (select2.min.js:2:35110)
>     at o.<anonymous> (select2.min.js:2:35635)
> ```
> 
> The list of already existing groups appear, but I'm also unable to click it.

I have same Issue

**Comment by frizcool** [comment]
i have same issue

`Uncaught TypeError: window.livewire.find is not a function
    at HTMLSelectElement.<anonymous> (settings:581:33)
    at HTMLSelectElement.dispatch (jquery.min.js:3:10316)
    at q.handle (jquery.min.js:3:8343)
    at Object.trigger (jquery.min.js:4:5628)
    at HTMLSelectElement.<anonymous> (jquery.min.js:4:6138)
    at Function.each (jquery.min.js:2:2715)
    at r.fn.init.each (jquery.min.js:2:1003)
    at r.fn.init.trigger (jquery.min.js:4:6114)
    at n.select (select2.min.js:2:35110)
    at o.<anonymous> (select2.min.js:2:35635)`

**Comment by frizcool** [comment]
> Hi,
> 
> Unfortunately I'm unable to add a specific setting to a group. I can't leave it empty and when searching I get the following Console error:
> 
> ```
>     at HTMLSelectElement.<anonymous> (settings:632:33)
>     at HTMLSelectElement.dispatch (jquery.min.js:3:10316)
>     at q.handle (jquery.min.js:3:8343)
>     at Object.trigger (jquery.min.js:4:5628)
>     at HTMLSelectElement.<anonymous> (jquery.min.js:4:6138)
>     at Function.each (jquery.min.js:2:2715)
>     at r.fn.init.each (jquery.min.js:2:1003)
>     at r.fn.init.trigger (jquery.min.js:4:6114)
>     at n.select (select2.min.js:2:35110)
>     at o.<anonymous> (select2.min.js:2:35635)
> ```
> 
> The list of already existing groups appear, but I'm also unable to click it.

I have same issue

**Comment by Odilbukh** [comment]
I have same issue

![image](https://user-images.githubusercontent.com/22895615/208055120-488e61dd-ce6b-4672-855e-37ffddf4a453.png)

**Comment by magarrent** [comment]
Same!

Console: 

`caught TypeError: $(...).select2 is not a function`
